S03 us23 admin add supp competition
WildCodeSchool/orleans-php-202009-project-uso-echecs pull request #100
Opened 2020-11-13 09:44 UTC by arnaudpilato

2020-11-16 10:22 UTC, MaevaPllt approved these changes

2020-11-16 19:51 UTC, sblondeau requested changes
j'ai le add et le delete dans une meme US... à diviser en 2 US et donc 2 PR !

2020-11-17 07:36 UTC, AmelieRoussel approved these changes

2020-11-17 08:30 UTC, sblondeau approved these changes

2020-11-17 08:30 UTC, merged