add prices and rates ok
WildCodeSchool/orleans-php-202009-project-uso-echecs pull request #101
Opened 2020-11-13 09:57 UTC by MaevaPllt

2020-11-13 13:47 UTC, sblondeau requested changes

2020-11-13 13:47 UTC, sblondeau commented on src/Controller/HomeController.php
> +        $prices = [
hum c'est pas en BDD ça ? :p ça serait mieux
et puis ou tu places le 'title' me semble pas logique car on le retrouve pas à chaque fois :/

2020-11-16 20:57 UTC, MaevaPllt commented on src/Controller/HomeController.php
> +        $prices = [
Corrections faites !

2020-11-16 21:34 UTC, AmelieRoussel approved these changes

2020-11-17 08:33 UTC, sblondeau requested changes
je pense que tu t'y prend mal sur tes tables
là il te faut une table Competition comme tu préfères 
dedans tu as tes champs price, category, rate etc ET un champ licence (qui contiendra A ou B), comme ça au final tu n'as qu'une table, qu'un tableau pour ta vue et une boucle dans ton Twig, c'est beaucoup plus propre et tu peux à terme ajouter une licence C, D, 4....

2020-11-18 11:44 UTC, MaevaPllt commented
Corrections faites !

2020-11-18 11:59 UTC, MatthieuBardet approved these changes

2020-11-18 12:48 UTC, sblondeau approved these changes

2020-11-18 12:48 UTC, merged