us ok
WildCodeSchool/orleans-php-202009-project-uso-echecs pull request #128
Opened 2020-11-17 15:53 UTC by AmelieRoussel

2020-11-17 16:21 UTC, MatthieuBardet approved these changes

2020-11-17 17:52 UTC, sblondeau requested changes
par ailleurs, attention à tes messages de commit car "us ok" n'est pas explicite

2020-11-17 17:52 UTC, sblondeau commented on src/Controller/AdminController.php
> +            $edits = array_map('trim', $_POST);
$members plutot que $edits ?

2020-11-17 17:52 UTC, sblondeau commented on src/Controller/AdminController.php
> +            'members' => $members
et là si tu envois que members ça doit etre bon. Au 1er affichage $members est ce qui vient de la bdd
ensuite c'est ce qui vient du post si le form a été soumis

2020-11-18 13:48 UTC, AmelieRoussel commented on src/Controller/AdminController.php
> +            'members' => $members
Si je fais ça le soucis c'est que je perds l'affichage de tous les membres en cas d'erreur (on les voit derrière la modale)

2020-11-18 15:37 UTC, MaevaPllt approved these changes

2020-11-18 16:00 UTC, sblondeau approved these changes

2020-11-18 16:00 UTC, merged