S03 us22 admin add edit competition
WildCodeSchool/orleans-php-202009-project-uso-echecs pull request #130
Opened 2020-11-17 21:35 UTC by arnaudpilato

2020-11-18 10:10 UTC, AmelieRoussel approved these changes

2020-11-18 12:51 UTC, sblondeau requested changes

2020-11-18 12:51 UTC, sblondeau commented on src/Controller/AdminCompetitionController.php
>              $errors[] = "Le champ concernant l'adrese ne doit pas être vide";
adresse

2020-11-18 12:51 UTC, sblondeau commented on src/Controller/AdminCompetitionController.php
>              $errors[] = "Erreur! Image trop volumineux.";
volumineuse

2020-11-18 12:51 UTC, sblondeau commented on src/Controller/AdminCompetitionController.php
>              $errors[] = "Erreur! Aucune image séléctionné.";
sélectionnée

2020-11-18 16:45 UTC, MaevaPllt approved these changes

2020-11-19 07:56 UTC, sblondeau approved these changes

2020-11-22 09:25 UTC, AmelieRoussel approved these changes

2020-11-23 07:57 UTC, merged