Fix max carousel news
WildCodeSchool/orleans-php-202009-project-uso-echecs pull request #214
Opened 2020-11-25 18:45 UTC by MatthieuBardet

2020-11-25 19:22 UTC, AmelieRoussel approved these changes

2020-11-26 08:00 UTC, sblondeau requested changes

2020-11-26 08:00 UTC, sblondeau commented on src/Model/NewsManager.php
> +        return $this->pdo->query('SELECT * FROM ' . $this->table . ' ORDER BY date DESC LIMIT 3')->fetchAll();
evite de mettre 3 en dur
ce que tu peux faire plutot c'est mettre un paramètre $limit=3 dans ta fonction, au moins c'est plus flexible

2020-11-26 09:13 UTC, MaevaPllt approved these changes

2020-11-26 09:26 UTC, sblondeau commented
passe pas les vérif
FILE: src/Model/NewsManager.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 55 | WARNING | Line exceeds 120 characters; contains 123 characters

2020-11-26 09:48 UTC, AmelieRoussel approved these changes

2020-11-26 10:30 UTC, sblondeau approved these changes

2020-11-26 10:30 UTC, merged