Fix max competition cards
WildCodeSchool/orleans-php-202009-project-uso-echecs pull request #215
Opened 2020-11-25 18:52 UTC by MatthieuBardet

2020-11-25 19:22 UTC, AmelieRoussel approved these changes

2020-11-26 08:07 UTC, sblondeau requested changes

2020-11-26 08:07 UTC, sblondeau commented on src/Model/CompetitionManager.php
> +        return $this->pdo->query("SELECT * FROM $this->table WHERE date > NOW() LIMIT 3")->fetchAll();
idem que la PR précédente

2020-11-26 09:03 UTC, AmelieRoussel approved these changes

2020-11-26 09:21 UTC, sblondeau approved these changes

2020-11-26 09:21 UTC, merged