Added variables and classes in CSS
WildCodeSchool/orleans-php-202009-project-uso-echecs pull request #29
Opened 2020-10-27 13:44 UTC by MatthieuBardet

2020-10-27 13:49 UTC, AmelieRoussel approved these changes

2020-10-27 13:50 UTC, arnaudpilato approved these changes

2020-10-28 08:58 UTC, sblondeau requested changes

2020-10-28 08:58 UTC, sblondeau commented on public/assets/css/style.css
> +    font-size: 0.875rem;
ça me parait petit... mais dans tous les cas ça peut etre une variable la font-size ;-)

2020-10-28 08:58 UTC, sblondeau commented on public/assets/css/style.css
> +    font-size: 2.5rem;
idem mets les font-size en variable (tu peux utiliser calc sur une meme variable aussi)

2020-10-28 09:38 UTC, AmelieRoussel approved these changes

2020-10-28 09:41 UTC, sblondeau approved these changes

2020-10-28 09:41 UTC, merged