S01 us15 caroussel news
WildCodeSchool/orleans-php-202009-project-uso-echecs pull request #32
Opened 2020-10-29 10:06 UTC by MatthieuBardet

2020-10-29 10:24 UTC, AmelieRoussel approved these changes

2020-10-29 10:57 UTC, sblondeau requested changes

2020-10-29 10:57 UTC, sblondeau commented on public/assets/css/style.css
> +    --image-gradient: linear-gradient(70deg, rgba(21,25,40,0.6), rgba(21,25,40,0.5970763305322129));
why ?

2020-10-29 10:57 UTC, sblondeau commented on src/View/Home/index.html.twig
> +        <div class="carousel-inner">
ces actus sont sensé etre administrables non ? 
donc il faut que les infos proviennent d'une BDD et non qu'elles soient mise en dur directement
donc il faut créer une table, saisir des données (à la main pour le moment). 
faire un requete en select
faire une boucle pour l'affichage.

2020-10-29 11:10 UTC, MatthieuBardet commented on public/assets/css/style.css
> +    --image-gradient: linear-gradient(70deg, rgba(21,25,40,0.6), rgba(21,25,40,0.5970763305322129));
C'est pour ajouter un dégradé sombre sur les images qui reçoivent du texte afin de le rendre lisible

2020-11-03 19:36 UTC, AmelieRoussel approved these changes

2020-11-04 09:24 UTC, AmelieRoussel approved these changes

2020-11-04 13:50 UTC, sblondeau requested changes

2020-11-04 13:50 UTC, sblondeau commented on public/assets/css/style.css
> +    --image-gradient: linear-gradient(70deg, rgba(21,25,40,0.6), rgba(21,25,40,0.5970763305322129));
tjs le soucis là

2020-11-04 14:07 UTC, AmelieRoussel approved these changes

2020-11-04 14:41 UTC, sblondeau approved these changes

2020-11-04 14:41 UTC, merged