S01 us03 contact form
WildCodeSchool/orleans-php-202009-project-uso-echecs pull request #38
Opened 2020-10-29 21:09 UTC by AmelieRoussel

2020-10-30 09:05 UTC, sblondeau requested changes

2020-10-30 09:05 UTC, sblondeau commented on public/assets/css/contact.css
> +    border-color: transparent !important;
pas de !important. JAMAIS :package:  tu as généralement tjs moyen de faire autrement ;-) 
ce n'est pas une bonne pratique car ça prend le pas sur toute notion de sélectivité dans ton CSS et "casse" la cascade

2020-10-30 09:05 UTC, sblondeau commented on public/assets/css/style.css
> +        font-size: 80%;
sur que c'est nécessaire ? dans ce cas je préfèrerais que tu changes juste la valeur de la variable qui te sers à définir la font-size (qui doit etre --text-font-size) ça exploite mieux les variables CSS.
sinon tu as ce genre de truc pour faire une font-size fluid, ce qui peut etre sympa aussi en fonction de tes besoins
https://css-tricks.com/snippets/css/fluid-typography/

2020-10-30 09:05 UTC, sblondeau commented on src/Controller/HomeController.php
> +        if (empty(htmlentities($message['firstname']))) {
non il ne faut pas que tu utilises htmlentites dans tes validations, ça sert seulement à l'affichage. Là en plus le risque c'est que ça change la taille de tes chaines de caractères car ça encode les caractères spéciaux sur des chaines plus longues. Donc enlève les. Ensuite coté affichage, plus besoin de les mettres car Twig le fait en automatique ;-)

2020-10-30 09:05 UTC, sblondeau commented on src/View/Contact/contact.html.twig
> +                <p class="required-field">(*) Champs obligatoires</p>
en terme d'UX, il vaut mieux mettre (optionnel) derrière les champs optionnel au lieux d'un asterisque devant les champ obligatoires (qui sont généralement beaucoup plus nombreux que les optionnels)

2020-10-30 09:20 UTC, MatthieuBardet approved these changes

2020-10-30 09:30 UTC, sblondeau requested changes
Question plus large, vous en faites quoi derrière des données du form de contact ? mail ? bdd ?

2020-10-30 09:30 UTC, sblondeau commented on src/View/Contact/contact.html.twig
> +                    <input type="text" class="lastname form-control" id="lastname" name="lastname"
j'ai l'impression que si tu as une erreur, tes champs se "vident" il faut que tu remette la value erronée saisie par le client (comme je l'avais montré en Live coding).

2020-11-01 10:56 UTC, MatthieuBardet approved these changes

2020-11-02 13:52 UTC, sblondeau approved these changes

2020-11-02 13:53 UTC, merged