S01 us05 formulaire adhesion
WildCodeSchool/orleans-php-202009-project-uso-echecs pull request #90
Opened 2020-11-10 20:57 UTC by MaevaPllt

2020-11-10 21:14 UTC, AmelieRoussel approved these changes

2020-11-12 08:10 UTC, sblondeau requested changes
l'image du header fait 17Mo !!! :p à réduire à 200Ko max
idem pour header_stage > 100 à 200ko

2020-11-12 08:10 UTC, sblondeau commented on src/Controller/HomeController.php
> +        if ((!is_numeric($_POST['inputPostalCode'])) || (strlen($_POST['inputPostalCode']) != 5)) {
pas de $_POST ! mais $data

2020-11-12 09:57 UTC, AmelieRoussel approved these changes

2020-11-12 14:27 UTC, sblondeau approved these changes

2020-11-12 14:27 UTC, merged